# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x06school\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n\x07Student\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tavg_grade\x18\x02 \x01(\x02\x12\'\n\x03\x64ob\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"?\n\tClassroom\x12\x0f\n\x07profile\x18\x01 \x01(\t\x12!\n\x08students\x18\x02 \x03(\x0b\x32\x0f.school.Student\"0\n\nClassStats\x12\x13\n\x0bnumstudents\x18\x01 \x01(\x05\x12\r\n\x05grade\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STUDENT']._serialized_start=59
  _globals['_STUDENT']._serialized_end=142
  _globals['_CLASSROOM']._serialized_start=144
  _globals['_CLASSROOM']._serialized_end=207
  _globals['_CLASSSTATS']._serialized_start=209
  _globals['_CLASSSTATS']._serialized_end=257
# @@protoc_insertion_point(module_scope)
